/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("com.wolfyscript.wolfyutils.spigot.java-conventions")
}

dependencies {
    compileOnly("org.spigotmc:spigot:1.16.4-R0.1-SNAPSHOT")
    compileOnly(project(":core"))
}

description = "nmsutil-v1_16_R3"
