import com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar
import java.util.*

/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("com.wolfyscript.wolfyutils.spigot.java-conventions")
    id("com.github.johnrengelman.shadow") version ("8.1.1")
    id("com.wolfyscript.devtools.docker.run") version ("2.0-SNAPSHOT")
    id("com.wolfyscript.devtools.docker.minecraft_servers") version ("2.0-SNAPSHOT")
}

description = "wolfyutils-spigot"

dependencies {
    api(apis.wolfyutils)
    implementation(project(":core"))
    implementation(project(":plugin-compatibility"))
    implementation(project(":nmsutil"))
    api(libs.bstats)
    api(libs.guice)
    api(libs.reflections)
    api(libs.javassist)
    api(libs.adventure.api)
    api(libs.adventure.minimessage)
    api(libs.adventure.platform.bukkit)
    api(libs.nbtapi.api)
    api(libs.nbtapi.data)

    testImplementation(project(":core"))
    testImplementation(testLibs.junit.jupiter)
    testImplementation(testLibs.mockito)
    testImplementation(testLibs.mockbukkit)
}

tasks.named<ProcessResources>("processResources") {
    expand(project.properties)
    duplicatesStrategy = DuplicatesStrategy.INCLUDE
}

// Default values for test server docker containers
dockerRun {
    name.set("test_minecraft_server")
    image.set("itzg/minecraft-server")
    daemonize.set(true)
    clean.set(true) // create a temporary server container

    ports("25565:25565")

    val serverEnv = mutableMapOf<String, String>()
    serverEnv["TYPE"] = "SPIGOT"
    serverEnv["VERSION"] = "1.20.1"
    serverEnv["GUI"] = "FALSE"
    serverEnv["EULA"] = "TRUE"
    serverEnv["MEMORY"] = "2G"
    serverEnv["USE_AIKAR_FLAGS"] = "TRUE"
    env(serverEnv)
    arguments.set(setOf("-it")) // Allow for console interactivity with 'docker attach'
}

minecraftServers {
    serversDir.set(file("./test_servers"))
    libName.set("${project.name}-${version}.jar")
    servers {
        register("spigot_1_17") {
            version.set("1.17.1")
            type.set("SPIGOT")
            ports.set(setOf("25565"))
        }
        register("spigot_1_18") {
            version.set("1.18.2")
            type.set("SPIGOT")
            ports.set(setOf("25566"))
        }
        register("spigot_1_19") {
            version.set("1.19.4")
            type.set("SPIGOT")
            ports.set(setOf("25567"))
        }
        register("spigot_1_20") {
            version.set("1.20.1")
            type.set("SPIGOT")
            ports.set(setOf("25568"))
        }
        // Paper test servers
        register("paper_1_20") {
            version.set("1.20.1")
            type.set("PAPER")
            ports.set(setOf("25569"))
        }
        register("paper_1_19") {
            version.set("1.19.4")
            type.set("PAPER")
            ports.set(setOf("25570"))
        }
    }
}

tasks.named<ShadowJar>("shadowJar") {
    dependsOn(project(":nmsutil").tasks.named("shadowJar"))

    archiveClassifier.set("")

    dependencies {
        include(dependency(apis.wolfyutils.get().toString()))
        include(dependency(apis.dataformat.hocon.get().toString()))
        include(dependency("${libs.bstats.get().group}:.*"))
        include(dependency("${libs.nbtapi.api.get().group}:.*"))
        include(project(":core"))
        include(project(":plugin-compatibility"))
        include(project(":nmsutil"))
    }

    relocate("org.bstats", "com.wolfyscript.utilities.bukkit.metrics")

    relocate("de.tr7zw.changeme.nbtapi", "com.wolfyscript.lib.de.tr7zw.nbtapi")
    relocate("de.tr7zw", "com.wolfyscript.lib.de.tr7zw")
}

tasks.named("test") {
    dependsOn.add(tasks.named("shadowJar"))
}
