/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "wolfyutils-spigot"

pluginManagement {
    repositories {
        mavenLocal()
        mavenCentral()
        gradlePluginPortal()
    }
}

include(":core")
include(":plugin-compatibility")
include(":nmsutil-v1_17_R1")
include(":nmsutil-v1_17_R1_P1")
include(":nmsutil-v1_18_R1")
include(":nmsutil-v1_18_R1_P1")
include(":nmsutil-v1_18_R2")
include(":nmsutil-v1_19_R3")
include(":nmsutil-v1_19_R1")
include(":nmsutil-v1_19_R2")
include(":nmsutil-v1_20_R1")
include(":nmsutil")

project(":nmsutil").projectDir = file("nmsutil")
project(":nmsutil-v1_17_R1").projectDir = file("nmsutil/nmsutil-v1_17_R1")
project(":nmsutil-v1_17_R1_P1").projectDir = file("nmsutil/nmsutil-v1_17_R1_P1")
project(":nmsutil-v1_18_R1").projectDir = file("nmsutil/nmsutil-v1_18_R1")
project(":nmsutil-v1_18_R1_P1").projectDir = file("nmsutil/nmsutil-v1_18_R1_P1")
project(":nmsutil-v1_18_R2").projectDir = file("nmsutil/nmsutil-v1_18_R2")
project(":nmsutil-v1_19_R1").projectDir = file("nmsutil/nmsutil-v1_19_R1")
project(":nmsutil-v1_19_R2").projectDir = file("nmsutil/nmsutil-v1_19_R2")
project(":nmsutil-v1_19_R3").projectDir = file("nmsutil/nmsutil-v1_19_R3")
project(":nmsutil-v1_20_R1").projectDir = file("nmsutil/nmsutil-v1_20_R1")
project(":plugin-compatibility").projectDir = file("plugin-compatibility")

dependencyResolutionManagement {
    versionCatalogs {
        // Third-party libraries
        create("libs") {
            // versions
            version("adventure", "4.14.0")

            // libs
            library("guice", "com.google.inject:guice:5.1.0")
            library("reflections", "org.reflections:reflections:0.10.2")
            library("javassist", "org.javassist:javassist:3.29.2-GA")
            library("adventure-api", "net.kyori", "adventure-api").versionRef("adventure")
            library("adventure-minimessage", "net.kyori", "adventure-text-minimessage").versionRef("adventure")
            library("adventure-platform-bukkit", "net.kyori", "adventure-platform-bukkit").version("4.1.2")
        }
        // Libraries only used for testing
        create("testLibs") {
            library("junit-jupiter", "org.junit.jupiter:junit-jupiter:5.9.0")
            library("mockito", "org.mockito:mockito-core:4.8.0")
            library("mockbukkit", "com.github.seeseemelk:MockBukkit-v1.18:2.85.2")
        }
        // internal apis
        create("apis") {
            library("wolfyutils", "com.wolfyscript.wolfyutils", "wolfyutilities").version("5.0-SNAPSHOT")
        }

    }
}