name: WolfyUtilities
version: '${project.version}'
main: com.wolfyscript.utilities.bukkit.WolfyCoreBukkit
api-version: 1.16
authors: [ WolfyScript ]
load: STARTUP

libraries:
  - "com.google.inject:guice:5.1.0"
  - "org.apache.commons:commons-lang3:3.12.0"
  - "it.unimi.dsi:fastutil:8.5.6"

loadbefore:
  - ChatColor
  - ChatColor2
  - StackableItems
  - DiSky
  - EpicWorldGenerator

softdepend:
  - Magic
  - LWC
  - PlotSquared
  - WorldGuard
  - MythicMobs
  - MMOItems
  - BungeeChat
  - mcMMO
  - Oraxen
  - ItemsAdder
  - PlaceholderAPI
  - eco
  - zAuctionHouseV3
  - SCore

permissions:
  wolfyutilities.command.query_debug:
    default: op
    description: "Command to debug NBT querries on the item in the hand"