name: WolfyUtilities
version: '${project.version}'
main: com.wolfyscript.utilities.bukkit.WolfyCoreBukkitBootstrap
api-version: 1.16
authors: [ WolfyScript ]
load: STARTUP

libraries:
  - "com.google.inject:guice:${depend_version.guice}"
  - "org.apache.commons:commons-lang3:3.12.0"
  - "org.javassist:javassist:${depend_version.javassist}"
  - "org.reflections:reflections:${depend_version.reflections}"
  - "com.fasterxml.jackson.core:jackson-databind:${depend_version.jackson}"
  - "net.kyori:adventure-api:${depend_version.adventure-api}"
  - "net.kyori:adventure-text-minimessage:${depend_version.adventure-api}"
  - "net.kyori:adventure-platform-bukkit:${depend_version.adventure-platform}"

loadbefore:
  - ChatColor
  - ChatColor2
  - StackableItems
  - DiSky
  - EpicWorldGenerator

softdepend:
  - Magic
  - LWC
  - PlotSquared
  - WorldGuard
  - MythicMobs
  - MMOItems
  - BungeeChat
  - mcMMO
  - Oraxen
  - ItemsAdder
  - PlaceholderAPI
  - eco
  - zAuctionHouseV3
  - SCore

permissions:
  wolfyutilities.command.query_debug:
    default: op
    description: "Command to debug NBT querries on the item in the hand"